version: "3.9"
services:
  temporal:
    container_name: temporal
    environment:
      POSTGRES_PASSWORD: temporal
      POSTGRES_USER: temporal
    image: leowmjw/temporalite
    networks:
      - temporal-network
    ports:
      - "7233:7233"
  temporal-admin-tools:
    container_name: temporal-admin-tools
    depends_on:
      - temporal
    environment:
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    image: temporalio/admin-tools:1.13.1
    networks:
      - temporal-network
    stdin_open: true
    tty: true
  temporal-web:
    container_name: temporal-web
    depends_on:
      - temporal
    environment:
      - TEMPORAL_GRPC_ENDPOINT=temporal:7233
      - TEMPORAL_PERMIT_WRITE_API=true
    image: temporalio/web:1.13.0
    networks:
      - temporal-network
    ports:
      - "8088:8088"
networks:
  temporal-network:
    driver: bridge
    name: temporal-network
