apiVersion: v1
kind: Service
metadata:
  name: "temporal"
  namespace: "temporalite"
  labels:
    app.kubernetes.io/name: "temporal"
    app.kubernetes.io/headless: 'true'
  annotations:
    # Use this annotation in addition to the actual field below because the
    # annotation will stop being respected soon but the field is broken in
    # some versions of Kubernetes:
    # https://github.com/kubernetes/kubernetes/issues/58662
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: ClusterIP
  publishNotReadyAddresses: true
  ports:
    - port: 7233
      targetPort: rpc
      protocol: TCP
      name: grpc-rpc
    - port: 9090
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: "temporal"

---

apiVersion: v1
kind: Service
metadata:
  name: "temporal-web"
  namespace: "temporalite"
  labels:
    app.kubernetes.io/name: "temporal-web"
    app.kubernetes.io/headless: 'true'
  annotations:
    # Use this annotation in addition to the actual field below because the
    # annotation will stop being respected soon but the field is broken in
    # some versions of Kubernetes:
    # https://github.com/kubernetes/kubernetes/issues/58662
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: ClusterIP
  publishNotReadyAddresses: true
  ports:
    - port: 8088
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: "temporal-web"
