name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Race
        run: go test -v -race ./...
        continue-on-error: true
      - name: Test
        run: go test -v -coverpkg=./... -covermode=atomic -coverprofile=coverage.out ./...
      - name: Coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # cgo is currently required by the upstream SQLite driver.
          # This case should be un-commented if and when cgo is
          # supported again.
          # - cgo: "0"
          - cgo: "1"
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Test
        env:
          CGO_ENABLED: ${{ matrix.cgo }}
        run: go test -v ./...
